---
- name: Install dependencies
  apt:
    name:
      - git
      - nginx
    state: present
  become: true

- name: Clone LightHouse repo
  git:
    repo: "{{ lighthouse_repo }}"
    dest: "{{ lighthouse_dest }}"
    update: yes

- name: Copy nginx config for LightHouse
  copy:
    src: lighthouse.conf
    dest: /etc/nginx/sites-enabled/lighthouse.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
